# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  tests in ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: cd packages/api && npm install

      - name: run api tests
        run: npm run test:api

  tests in windows-latest:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: cd packages/api && npm install

      - name: run api tests
        run: npm run test:api
